<?php

$array = [
    'm_payment_id' => '2',
    'pf_payment_id' => '68837816',
    'payment_status' => 'CANCELLED',
    'item_name' => 'Best Agent Test Monthly Subscription',
    'item_description' => NULL,
    'custom_str1' => 'App\\Models\\User',
    'custom_str2' => 'Monthly Plan',
    'custom_str3' => NULL,
    'custom_str4' => NULL,
    'custom_str5' => NULL,
    'custom_int1' => '1',
    'custom_int2' => '2',
    'custom_int3' => NULL,
    'custom_int4' => NULL,
    'custom_int5' => NULL,
    'name_first' => NULL,
    'name_last' => NULL,
    'email_address' => 'eugene@vander.host',
    'merchant_id' => '13741656',
    'token' => '50ad36e9-22a3-47fe-8385-5677e49ee025',
    'signature' => '91d6b4f2edfacbd68b126719ea16cc34',
];
